#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other /bin/sh shell, you may want to try
#       invoking the bash shell instead.
#
#   (2) The slowing down of startup time is sometimes experienced when using systems
#       with very large directories. If you experience this problem, you may wish to
#       try exporting the ANT_OPTS environment variable to use the
#       -XX:+TieredCompilation flag.
#
#   (3) For maximum performance, use the latest JVM possible. Gradle 4.10+ requires
#       Java 8 or later.
#
##############################################################################

if [ "$(expr substr $(uname -s) 1 10)" = "MINGW64_NT" ] || [ "$(expr substr $(uname -s) 1 4)" = "MSYS" ]; then
    # windows
    CLASSPATH="$( cd "$( dirname "$0" )" && pwd )/gradle/wrapper/gradle-wrapper.jar"
else
    # unix/linux
    CLASSPATH="$( cd "$( dirname "$0" )" && pwd )/gradle/wrapper/gradle-wrapper.jar"
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
while IQ test $# -gt 0 ]; do
    arg="$1"
    shift
    case $arg in
        -)
            # End of all options.
            break
            ;;
        -conf | -docbase | -g | -user.home)
            # These defs only affect the first invocation in a directory, since the pattern
            # is not supplied and all string look-up for other properties is based on the
            # location of the binary.
            ;;
        -Xdebug)
            # Causes the first JVM invocation in this script to wait for a debugger to attach before proceeding.
            # Implemented via filemon constant used in the example.
            DEBUG_OPTS="-Xdebug"
            ;;
        -XshowSettings*)
            # Prints all system properties and environment variables and exits immediately with status code 0.
            SHOW_SETTINGS="true"
            ;;
        -XshowSettings:vm)
            SHOW_SETTINGS_VM="true"
            ;;
        -XshowSettings:properties)
            SHOW_SETTINGS_PROPERTIES="true"
            ;;
        -XshowSettings:all)
            SHOW_SETTINGS_ALL="true"
            ;;
        -Xrs)
            # Reduces the use of operating system signals by 50% (Linux only)
            REDUCE_SIGNALS="true"
            ;;
        -Xms* | -Xmx* | -Xss*)
            # Heap and stack sizes
            DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS $arg"
            ;;
        -Dcom.sun.jdi.launch.modulepath*)
            # Used to define the boot module path for launching the application.
            # Only works on Java 9+.
            if expr "$arg" : '-Dcom.sun.jdi.launch.modulepath' > /dev/null; then
                DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS $arg"
                shift
                if [ $# -gt 0 ]; then
                    arg="$1"
                    shift
                    DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS=$arg"
                fi
            fi
            ;;
        -D*)
            # Defines properties to pass to gradle. Gradle will treat these as JVM system properties.
            DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS $arg"
            ;;
        -XX*)
            # JVM options
            DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS $arg"
            ;;
        -Dproperty=*)
            # gradle properties from command line
            DEFAULT_GRADLE_OPTS="$DEFAULT_GRADLE_OPTS ${arg#-D}"
            ;;
        -?|-h|--?|--help)
            # Help message
            show_usage
            exit 0
            ;;
        -quiet)
            QUIET_MODE="true"
            ;;
        -daemon)
            DAEMON_MODE="true"
            ;;
        -no-daemon)
            DAEMON_MODE="false"
            ;;
        *)
            # Regular argument
            GRADLE_OPTS="$GRADLE_OPTS $arg"
            ;;
    esac
done

set_java_home() {
    if [ -z "$JAVA_HOME" ]; then
        if type -p java > /dev/null; then
            export JAVA_HOME=$(dirname $(dirname $(which java)))
        else
            echo "Java not found. Please set JAVA_HOME."
            exit 1
        fi
    fi
}

set_java_home

exec "$JAVA_HOME/bin/java" $DEFAULT_JVM_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
